const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://media.istockphoto.com/id/161170090/photo/pancakes-with-berries-and-maple-syrup.jpg?s=612x612&w=0&k=20&c=8EctScsN7q5UmxeXPNBnYN1eFmJmgmp2bE0OIq_czwM=',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-m/1280/1a/86/9d/db/canada-s-diner-double.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://b.zmtcdn.com/data/dish_photos/6b5/7cc1c87b6fbb22ed46a06872ca9da6b5.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://images.livemint.com/img/2019/01/22/600x338/8e60a944-1e33-11e9-b09d-ec8e717504b6_1548182310697_1548182334634.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://domf5oio6qrcr.cloudfront.net/medialibrary/12027/d02feeb0-8e73-48fb-946f-5c01d1813a41.png',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://i.pinimg.com/564x/85/ec/a7/85eca742fc516a74e0f7187a43763b85--oreo-cheesecake-recipes-oreo-dream-extreme-cheesecake-recipe.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://external-preview.redd.it/H5wUsbQwYSKQYxJII7ARXb6Jvk_-Xb30tyjbwf_MuZU.jpg?width=640&crop=smart&auto=webp&s=27dd2ccf6e6a691dcb41360b83d193952e9e7870',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://insanelygoodrecipes.com/wp-content/uploads/2021/04/Homemade-Pecan-Pie-800x530.png',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://img.freepik.com/premium-photo/courier-mask-delivers-box-food-items-service-delivery-terms-quarantine_197602-374.jpg?w=2000',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;
  